#!/bin/bash
#
# Copy to usb - Copia os arquivos selecionados para um dispositivo usb.
#
# Autor: Flávio Amieiro
#
#
# Versão 0.1 - Aparentemente funcional. Ainda não tenho muita certeza da
#              precisão do método de determinação do diretório de destino. 
#              Ainda bastante baseado em POG.

# Diretório para o qual serão enviados os arquivos. Edite esta linha de acordo
# com a sua necessidade
DIR=`cat /etc/mtab | grep sdb1 | cut -d' ' -f2`

# Arquivo temporário onde são armazenados os nomes dos arquivos
# selecionados:
TMP_FILE="/tmp/copytousb.tmp"


# Gravando o nome dos arquivos selecionados no arquivo temporário:
echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" > "$TMP_FILE"


# Lendo cada linha do arquivo temporário, atribuindo o valor lido à variável
# arquivo_atual, e copiando esse arquivo para a pasta de destino.
# Em caso de erro, um diálogo mostra os arquivos que não foram copiados
while read LINHA; do
    [ "$LINHA" ] || continue # ignora linhas vazias
    arquivo_atual="$LINHA"
    cp "$arquivo_atual" "$DIR" || zenity --warning \
    --text="Não foi possível copiar o arquivo $arquivo_atual. \nProvavelmente o diretório de destino nao foi encontrado"
done < "$TMP_FILE"

# Removendo o arquivo temporário
rm "$TMP_FILE"
