#!/bin/bash
#
# Copy to usb - Copia os arquivos selecionados para um dispositivo usb.
#
# Autor: Flávio Amieiro
#
#
# Versão 0.1 - Aparentemente funcional. Ainda não tenho muita certeza da
#              precisão do método de determinação do diretório de destino. 
#              Ainda bastante baseado em POG.
#
# Versão 0.2 - Modificado o método de determinação do diretório de destino.
#              Agora o script procura por /dev/sd** (na versão anterior estava
#              preso ao sdb*, então pontos pela generalização) que tenha seu
#              ponto de montagem em /media (padrão pelo menos no Ubuntu e no
#              Fedora). Ainda não me convenceu.
#              Confere se o diretório de destino existe. Se não, mostra um erro.
#
# Versão 0.3 - Adicionado suporte a diretórios.
#
# Versão 0.4 - Caso o dispositivo não seja encontrado automaticamente, dá ao
#              usuário a opção de indicar o caminho dele.
#
#


# Diretório para o qual serão enviados os arquivos. Como se pode ver pelo
# histórico de versões, essa solução ainda não me convence.
DIR=$(cat /etc/mtab | grep '/dev/sd..' | grep /media | cut -d' ' -f2)

# Arquivo temporário onde são armazenados os nomes dos arquivos
# selecionados:
TMP_FILE="/tmp/copytousb.tmp"


# Gravando o nome dos arquivos selecionados no arquivo temporário:
echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" > "$TMP_FILE"


# Testando para ver se o diretório de destino existe. Se não existir, dá ao
# usuário a opção de escolher o caminho correto.
if test -d "$DIR"
then
    echo "O dispositivo de destino existe"
else
    # Diálogo que pergunta ao usuário se ele quer escolher manualmente o ponto
    # de montagem do dispositivo. Retorna a variável $ESCOLHER com "ok" ou
    # "cancel", dependendo do que o usuário escolher.
    ESCOLHER=$(zenity --question --title="Copy to usb" --text="O dispositivo de \
destino não foi encontrado automaticamente.\nDeseja procurar o ponto de \
montagem manualmente?" \
    && echo "ok" \
    || echo "cancel")
    
    # Se o usuário quiser escolher o ponto de montagem, mostra um diálogo para
    # isso, caso contrário, termina o programa com status 1.
    if test $ESCOLHER = ok
    then
        DIR=$(zenity --file-selection --title="Copy to usb - escolha o ponto de \
montagem" \
        --directory --filename="/media")
    else
        exit 1
    fi
fi


# Lendo cada linha do arquivo temporário, atribuindo o valor lido à variável
# arquivo_atual, e copiando esse arquivo para a pasta de destino.
# Em caso de erro, um diálogo mostra os arquivos que não foram copiados
while read LINHA; do
    [ "$LINHA" ] || continue # ignora linhas vazias
    arquivo_atual="$LINHA"
    if test -f "$arquivo_atual" # se for um arquivo...
    then
        cp "$arquivo_atual" "$DIR" || zenity --error \
        --text="Não foi possível copiar o arquivo $arquivo_atual."
    elif test -d "$arquivo_atual" # se for um diretório...
    then
        cp -r "$arquivo_atual" "$DIR" || zenity --error \
        --text="Não foi possível copiar o diretório $arquivo_atual."
    fi
done < "$TMP_FILE"

# Removendo o arquivo temporário
rm "$TMP_FILE"
